const p = (x, z) => ({ x, z });
const line = (speaker, text) => ({ speaker, text });

export const DISTRICTS = {
  signal: { name: "Breakwater Marina", theme: "Listen before you repair", sky: 0x79c4dd, fog: 0xb6dce3, ground: 0xddc69b, sun: 0xffe4bb, paving: 0x947659, props: ["palm", "salvage_tower"], restored: "Public communications restored. BOLT has a home to return to." },
  tide: { name: "Tidal Gardens", theme: "Nobody gets left below the tide line", sky: 0x78c9ca, fog: 0xb5dad5, ground: 0xc9ceab, sun: 0xffedcf, paving: 0x859c8a, props: ["coral_cluster", "reef_arch"], restored: "The tide shelters are open. The little sea community is together again." },
  defense: { name: "Salvage Commons", theme: "A defense line is a promise to your neighbors", sky: 0xc99786, fog: 0xd6bca5, ground: 0xad9a86, sun: 0xffc894, paving: 0x526674, props: ["salvage_tower", "twin_thrusters"], restored: "The repair commons belongs to everyone, including rebooted scouts." },
  skyway: { name: "Windward Causeway", theme: "An open route is better than a locked gate", sky: 0x88aed7, fog: 0xc4d3e3, ground: 0xc7bc9e, sun: 0xf9e7c3, paving: 0x6a858c, props: ["reef_arch", "beacon"], restored: "AURORA can carry supplies to the outer islands again." },
  siege: { name: "LUMA Watch", theme: "Protection without trust is only another cage", sky: 0x293956, fog: 0x637696, ground: 0x919898, sun: 0xc0d8ff, paving: 0x536b87, props: ["beacon", "salvage_tower"], restored: "The Warden chooses to guard an open island. The festival can finally begin." },
};

export const STAGE_STORY = {
  wake: { stakes: "Bring your first friend back online.", story: "Every radio on the beach went quiet at once. BOLT's dock has one last message: do not leave anyone behind. KAI starts with the smallest repair.", beats: ["Recover three charged cells", "Reconnect BOLT's dock"], outcome: "BOLT wakes with a sand-filled speaker and an intact rescue map. The blackout came from the island's own security network.", dialogue: [line("LUMA", "KAI, start with BOLT. Three charged cells should wake his dock."), line("BOLT", "Emergency message: if I am snoring, please call it a diagnostic.")] },
  trail: { stakes: "Discover who silenced the island.", story: "The marina transmitter works, but its relay heads face the wrong way. Turn the outputs and watch where the beam actually travels.", beats: ["Rotate relay arrows with Q or E", "Carry the cyan beam into the receiver"], outcome: "A restored recording names the Warden's SUNDOWN protocol: isolate all districts, suspend all rescue traffic. LUMA recognizes her old partner's voice.", dialogue: [line("LUMA", "Cyan is powered. Turn each arrow toward the next relay, then the receiver."), line("KAI", "We can turn a relay before it has power. The beam will tell us when the route connects.")] },
  fragment: { stakes: "Restore a public signal without abandoning damaged robots.", story: "A patrol is confiscating every transmitter it can find. Their cores are damaged; a careful reboot can turn an attacker into a neighbor.", beats: ["Pick up a weapon or use your pulse", "Reboot the patrol", "Restore the marina beacon"], outcome: "The first network function is LISTEN. AURORA carries its repair patch to the Tidal Gardens, where several rescue calls have gone unanswered.", dialogue: [line("BOLT", "Weapon crates up ahead. Loud bubbles, quiet intentions."), line("KAI", "Reboot the patrol. We are fixing the network, not erasing its people.")] },
  "little-wave": { stakes: "Learn what the blackout has cost the smallest residents.", story: "The tide shelter stopped answering its rescue calls. Three friends wait among the garden pools. Bring them to the raised green shelter one at a time.", beats: ["Use E beside a stranded friend", "Carry them into the green shelter"], outcome: "The shelter lights turn on. The octopus has been holding everyone's emergency snacks above the water; nobody wants to ask which arm held what.", dialogue: [line("LUMA", "Use to lift a friend. Use again inside the green shelter to set them down."), line("BOLT", "I have checked the shelter. Dry floor. Good acoustics. Excellent barking.")] },
  "split-current": { stakes: "Choose safe routes instead of obeying a single arrow.", story: "Two shelters now answer the radio. Surge drones sweep the open garden. Choose the nearest safe shelter, or take the longer quiet route around the red rings.", beats: ["Read the moving surge rings", "Choose either green shelter", "Deliver all four friends"], outcome: "The rescue team proves that a network can share responsibility. One closed central shelter was never safer than two open ones.", dialogue: [line("BOLT", "Two green shelters. Either one is safe; take the route with a gap in the red rings."), line("LUMA", "A shorter route is not always a safer route. You choose.")] },
  "everyone-home": { stakes: "Reopen the flood-warning network after everyone is safe.", story: "The isolation beacon keeps sending false evacuation orders. Rescue the last four friends before touching it; shutting it down early would also silence their location tags.", beats: ["Bring four friends to either shelter", "Disable the orange isolation beacon"], outcome: "SHELTER joins LISTEN in the recovery patch. The tide warnings are trustworthy again. A real distress call arrives from the Salvage Commons.", dialogue: [line("KAI", "Friends first, beacon second. Their location tags still need its power."), line("BOLT", "Four passengers, zero passengers left behind. That is my kind of arithmetic.")] },
  boardwalk: { stakes: "Give the repair community time to recover.", story: "The patrol followed the rescue broadcast to the Commons. The mechanics need a defense line while they repair the district relay.", beats: ["Build both solar turrets at your own pace", "Press Use when ready", "Support the line with your weapon"], outcome: "The relay stays online. The first rebooted scout brings spare fuses instead of taking them. Cooperation has a measurable power output.", dialogue: [line("LUMA", "No wave starts until you say ready. Gold pads show the turret positions."), line("KAI", "The turrets cover the approaches. I will catch anything they miss.")] },
  approaches: { stakes: "Hold a shared space against a coordinated patrol.", story: "The Warden reroutes armored units down three marked approaches. Every turret needs support; chasing one drone too far can leave another lane open.", beats: ["Prepare three turret positions", "Read the approach lines", "Intercept armored units before the relay"], outcome: "The Commons remains open. The Rust Captain arrives carrying a signed order: protection requires total isolation. LUMA asks KAI to recover the rest of the log.", dialogue: [line("BOLT", "Three lanes. Watch the whole line, not just the loudest robot."), line("LUMA", "Armored units need three hits. Support the turret that is under pressure.")] },
  captain: { stakes: "Recover the order log without destroying its keeper.", story: "The Captain's charge shield cannot be forced open. Let it commit to a charge, step aside, then reboot the exposed core.", beats: ["Wait for the fixed orange charge line", "Dash sideways", "Attack only the exposed cyan core"], outcome: "The log reveals a storm from years ago. The Warden saved LUMA then, but its emergency isolation rule never ended. COOPERATE is the third repair function.", dialogue: [line("LUMA", "That shield is a storm door. Let the Captain open it by charging past you."), line("KAI", "A missed charge, an exposed core, a careful repair. No shortcuts.")] },
  sprint: { stakes: "Reopen the courier route.", story: "AURORA cannot safely navigate the disconnected causeway. Light its approach gates along the bends so the courier can find a route home.", beats: ["Follow the numbered causeway gates", "Save your dash for the open straights"], outcome: "The first approach lights return. AURORA answers with a cargo manifest and a deeply offended autopilot.", dialogue: [line("AURORA", "I can fly through a storm. I cannot fly through missing directions."), line("BOLT", "Gold gate next. Bend first, dash second.")] },
  cargo: { stakes: "Recover supplies the other districts are counting on.", story: "A damaged cargo rack scattered five signal cells along the service route. Recover the drifting cells while AURORA circles above.", beats: ["Follow the service-route cargo trail", "Pulse all five drifting cells"], outcome: "The cargo contains medicine packs, spare joints and one extremely well-packaged squeaky toy. BOLT calls the entire shipment essential.", dialogue: [line("AURORA", "Five signal cells mark the lost cargo. The compass follows the nearest one."), line("BOLT", "If you find something that squeaks, that is sensitive rescue equipment.")] },
  storm: { stakes: "Connect the outer islands before confronting the Warden.", story: "Surge drones cross the final causeway bends. Read the gaps and finish the eight-gate route. A clean crossing is a bonus, not a reason to abandon the mission.", beats: ["Read red zones before crossing", "Complete the eight-gate storm route"], outcome: "RECONNECT reaches the outer islands. AURORA returns with their answer: nobody wants to be protected by being forgotten. LUMA asks to speak to the Warden herself.", dialogue: [line("LUMA", "You can take a hit and still finish. A safe arrival matters more than a perfect score."), line("AURORA", "Approach lights received. Coming home.")] },
  "dark-beach": { stakes: "Keep LUMA awake long enough to reach her old partner.", story: "The Warden cuts power to LUMA Watch. Backup cells remain in three service yards, but patrols are closing in. Restore the relay before entering the core court.", beats: ["Recover three backup cells", "Keep patrols away from your route", "Restore LUMA's gold relay"], outcome: "LUMA's light steadies. She remembers the Warden carrying her lens through the old storm, and refuses to reduce that memory to an enemy label.", dialogue: [line("LUMA", "The Warden once carried my lens through a storm. There is still someone in there worth reaching."), line("KAI", "Then we keep the light on until it can hear you.")] },
  core: { stakes: "Make the recovered functions work as one network.", story: "Four districts have sent their repairs. Route the core relays into the lighthouse receiver so LUMA can deliver them as one coherent signal.", beats: ["Inspect which relays receive power", "Rotate each output toward the next device", "Power the lighthouse receiver"], outcome: "LISTEN, SHELTER, COOPERATE and RECONNECT become one signal. The last function cannot be forced into place: the Warden must be allowed to trust the community.", dialogue: [line("KAI", "The same relay rule, a new layout. Watch the beam, not an activation order."), line("LUMA", "Once the receiver lights, I can speak to it. Keep the core safe.")] },
  signalbreak: { stakes: "Repair the rule, not just the machine.", story: "Protect the core while LUMA opens a channel. Reboot the Warden's charge shield, then install the shared-signal patch by hand. Its last order must be a choice to keep the island open.", beats: ["Defend the core from six scouts", "Checkpoint: confront the Warden", "Clear its escort and install the repair with E", "Send the festival signal from the rocket"], outcome: "WARDEN: Protection protocol revised. Keep the routes open. Ask before closing a door. AURORA carries the festival signal over an island full of imperfect, very much awake friends.", dialogue: [line("LUMA", "Protect the core. When this first wave is clear, we will secure a checkpoint."), line("KAI", "Then I reboot its shield, clear the escort, and install the repair myself."), line("BOLT", "And then the festival. I have been practicing my dignified walk.")] },
};

export const STAGE_LAYOUTS = {
  trail: { type: "relay", count: 3, positions: [p(-8, 5), p(1, 5), p(1, -5)], labels: ["Harbor relay", "Garden relay", "Courier relay"], receiver: p(11, -5), source: p(-8, 12), turns: [0, 1, 2], objective: "Turn the relay arrows with Q or E until the powered beam reaches the receiver." },
  core: { type: "relay", count: 3, positions: [p(-8, 7), p(-8, -5), p(5, -5)], labels: ["Listen / shelter", "Cooperate", "Reconnect"], receiver: p(5, -12), source: p(-14, 7), turns: [2, 3, 1], objective: "Rotate the core relays to carry power into the lighthouse receiver." },
  "split-current": { shelters: [p(-12, -7), p(12, -7)] },
  "everyone-home": { count: 4, positions: [p(-11, 6), p(-5, 10), p(7, 9), p(12, 1)], shelters: [p(-12, -7), p(3, -9)], hazards: true, objective: "Rescue four friends into either green shelter, then disable the orange isolation beacon." },
  sprint: { gatePositions: [p(-8, 11), p(-12, 4), p(-6, -3), p(2, -9), p(11, -5), p(10, 5)], objective: "Light all six numbered approach gates in order along the causeway bends." },
  cargo: { count: 5, positions: [p(-10, 8), p(-9, -2), p(-2, -10), p(8, -6), p(11, 6)], objective: "Recover five drifting courier cells along the service route." },
  storm: { count: 8, minShield: null, gatePositions: [p(-6, 12), p(-12, 7), p(-10, -1), p(-4, -7), p(4, -11), p(11, -5), p(11, 3), p(4, 9)], objective: "Follow all eight storm gates. Dodge the red zones; a perfect crossing is optional." },
  signalbreak: { objective: "Protect the core, reboot the Warden and its escort, install the free repair with E, then send the festival signal." },
};

export function storyFor(item) { return DISTRICTS[item?.chapter?.id] && item.stage.type !== "roam" ? STAGE_STORY[item.stage.id] : null; }
export function journalEntries(progress, stages) { return stages.filter(item => progress.completed.includes(`${item.chapter.id}:${item.stage.id}`)).map(item => ({ title: item.stage.name, district: DISTRICTS[item.chapter.id].name, text: STAGE_STORY[item.stage.id].outcome })); }
export function isStoryMode(item, progress) { return Boolean(storyFor(item)) && progress.settings.campaignMode !== "challenge"; }
